apiVersion: v1
kind: Secret
metadata:
  name: db-socialdev
  namespace: socialdev
type: Opaque
stringData:
  DB_HOST: "10.194.1.43"
  DB_PORT: "5432"
  DB_NAME: postgres
  DB_USER: postgres
  DB_PASSWORD: "P@ssw0rd@123"
