apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: socialdev
type: Opaque
stringData:
  JWT_SECRET: "ONEoLZ9Ik6O8UU9iNEA7pQIv0nMi1FyoA6dAaxvxek7nAqcRSVmGcQKS6ff4Ubzx"
  JWT_REFRESH_SECRET: "CHsp7o9D+IBVVqymKiE3ZPv3vM19tEuHvRH3ed2grOE/c5te0kcffnaOz7CQ0Tc2"
