apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: socialdev
type: Opaque
stringData:
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: "minioadmin@123"
  MINIO_ENDPOINT: "10.194.1.44:9000"
  MINIO_REGION: us-east-1
  MINIO_USE_SSL: "false"
