apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: socialdev
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "P@ssw0rd@123"
  POSTGRES_DB: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: socialdev
type: Opaque
stringData:
  JWT_SECRET: dev-secret-change-me
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: minioadmin
