apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: dev-paramee
data:
  config.yaml: |
    tunnel: 17b067d7-3423-4308-be1f-b1c21fb4bb79
    credentials-file: /etc/cloudflared/credentials/credentials.json
    no-autoupdate: true
    ingress:
      - hostname: socialdev.parameedev.online
        service: http://kong-proxy.kong.svc.cluster.local:80
      - service: http_status:404
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: dev-paramee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config/config.yaml
            - run
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared/config
              readOnly: true
            - name: credentials
              mountPath: /etc/cloudflared/credentials
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: config
          configMap:
            name: cloudflared-config
        - name: credentials
          secret:
            secretName: tunnel-credentials
