apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: socialdev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      initContainers:
        - name: wait-postgres
          image: busybox:1.36
          command: ["sh", "-c", "until nc -z 10.194.1.43 5432; do sleep 2; done"]
      containers:
        - name: auth
          image: socialdevapp-auth:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              value: socialdev_auth
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_SECRET
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_BROKERS
            - name: AUTH0_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AUTH0_DOMAIN
            - name: AUTH0_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AUTH0_CLIENT_ID
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: socialdev
spec:
  selector:
    app: auth
  ports:
    - port: 8080
      targetPort: 8080
